name: Flask Docker CI
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Initialize Python 3.8
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.8
    - name: Login to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Build and Push Flask Frontend
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./fyp-flask/
        file: ./fyp-flask/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPO_FLASK }}:latest,${{ secrets.DOCKER_REPO_FLASK }}:${{github.run_number}}

    - name: Build and Push Flask Frontend
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./fyp-spark/
        file: ./fyp-spark/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPO_SPARK}}:latest,${{ secrets.DOCKER_REPO_SPARK }}:${{github.run_number}}
